title: Munio.pm Status Überblick
buildFuture: true
defaultContentLanguage: de
languageCode: de
baseURL: https://munio.pm
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Kursversorgung
      description: >-
        Prüft, ob alle Kurse der Hausmeinung und in Bestand befindlichen Papiere
        up-to-date sind
      category: GSAM
    - name: Kursversorgung
      description: >-
        Prüft, ob alle Kurse der Hausmeinung und in Bestand befindlichen Papiere
        up-to-date sind
      category: Bank für Kirche und Diakonie
    - name: Kursversorgung
      description: Kursversorgung aktuell bei Smavesto
      category: Smavesto
    - name: FIX Verbindung
      description: FIX Verbindung für das Ordering aktuell
      category: Smavesto
    - name: Datenimport BaaderBank
      description: checkt ob der Datenimport bei der BaaderBank durchgelaufen ist
      category: Smavesto
    - name: Kursversorgung
      category: Hauck & Aufhäuser
      description: Kursversorgung für H&A
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/dser-logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: true
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: none
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: GSAM
      description: Überwachungsmodule GSAM
      closed: false
    - name: Smavesto
      description: Überwachun
    - name: Bank für Kirche und Diakonie
      description: Überwachungsmodule der Bank für Kirche und Diakonie
      closed: false
    - name: Merck Finck
      description: Überwachungsmodule der Merck Finck Bank
      closed: false
    - name: Hauck & Aufhäuser
      description: Überwachungsmodule für H&A
      closed: false
  description: Wir überwachen permanent unsere System und melden Ausfälle über diesen Kanal
  enableCustomHTML: true
  useLargeHeaderDesign: false
